[package]
name = "geometry-rays"
version = "0.1.0"
edition = "2024"

[dependencies]
raylib = "5.0.2"
rand = "0.9.0"
rodio = "0.20.1"
webbrowser = "1.0.4"
reqwest = { version = "0.12.15", features = ["socks"] }
tokio = { version = "1.44.1", features = ["full"] }
tokio-process = "0.2.5"