[package]
name = "geometry-rays"
version = "0.1.0"
edition = "2024"

[dependencies]
raylib = "5.5.1"
rodio = "0.20.1"
webbrowser = "1.0.4"
tokio = { version = "1.45.0", features = ["full"] }
ez-reqwest = "1.0.0"
