[package]
name = "geometry-rays"
version = "0.1.0"
edition = "2021"

[dependencies]
raylib = "5.0.2"
rand = "0.8.5"
rodio = "0.20.1"
webbrowser = "1.0.3"
reqwest = { version = "0.12.12", features = ["socks"] }
tokio = { version = "1", features = ["full"] }
tokio-process = "0.2.5"